language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-27.0.2

    # The SDK version used to compile your project
    # - android-22
    #- android-24
    #- android-25
    - android-27

    # Additional components
    #- extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    #- addon-google_apis-google-19
    #- add-on
    #- extra

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    #- sys-img-armeabi-v7a-android-22
    #- sys-img-armeabi-v7a-android-17
    - sys-img-armeabi-v7a-android-25
  
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'intel-android-extra-license.+'
    - 'android-sdk-preview-license-52d11cd2'
    - 'google-gdk-license-.+'

  # This fixes the required permissions for gradle build.
  before_install:
    - chmod +x gradlew

  install:
    # Check install section: http://docs.travis-ci.com/user/build-configuration/#install
    # If you'd like to skip the install stage entirely, set it to true and nothing will be run.
    #- true

  #before_script:
    # Create and start emulator
    #- echo no | android create avd --force -n test -t android-25 --abi armeabi-v7a
    #- emulator -avd test -no-skin -no-audio -no-window &
    #- android-wait-for-emulator
    #- adb shell input keyevent 82 &

  branches:
    only:
      - master
      - dev

script:
  # By default Travis-ci executes './gradlew build connectedCheck' if no 'script:' section found.
  - ./gradlew build --stacktrace 
  # add --info or --verbose for more output